<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ComicReaderAdminBundleEntityT_RightProxy extends \ComicReader\AdminBundle\Entity\T_Right implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setR($r)
    {
        $this->__load();
        return parent::setR($r);
    }

    public function getR()
    {
        $this->__load();
        return parent::getR();
    }

    public function setU($u)
    {
        $this->__load();
        return parent::setU($u);
    }

    public function getU()
    {
        $this->__load();
        return parent::getU();
    }

    public function setV($v)
    {
        $this->__load();
        return parent::setV($v);
    }

    public function getV()
    {
        $this->__load();
        return parent::getV();
    }

    public function setD($d)
    {
        $this->__load();
        return parent::setD($d);
    }

    public function getD()
    {
        $this->__load();
        return parent::getD();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'Name', 'R', 'U', 'V', 'D');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}