<?php

namespace ComicReader\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function searchAuthor($value)
    {
        $qb = $this->_em->createQueryBuilder();
    
        $qb->select('a')
            ->from('ComicReaderAdminBundle:Author', 'a')
            ->where('a.Name LIKE :value')
            ->setParameter('value', '%'.$value.'%');
    
        return $qb->getQuery()->getResult();
    }
}