<?php

namespace ComicReader\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
}