<?php

namespace ComicReader\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
    public function searchMarks($bookid)
    {
        $qb = $this->_em->createQueryBuilder();
    
        $qb->select('m')
            ->from('ComicReaderAdminBundle:Mark', 'm')
            ->where('m.FK_Book = :value')
            ->setParameter('value', $bookid);
    
        return $qb->getQuery()->getResult();
    }
}