<?php

namespace ComicReader\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * T_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_UserRepository extends EntityRepository
{
    public function authentificate($login, $password)
    {
        $qb = $this->_em->createQueryBuilder();
    
        $qb->select('u')
            ->from('ComicReaderAdminBundle:T_User', 'u')
            ->where('u.Login = :login')
            ->andWhere('u.Password = :password')
            ->setParameter('login', $login)
            ->setParameter('password', $password);
    
        return $qb->getQuery()->getResult() != null;
    }
    
    public function getUser($login)
    {
        $qb = $this->_em->createQueryBuilder();
    
        $qb->select('u')
            ->from('ComicReaderAdminBundle:T_User', 'u')
            ->where('u.Login = :login')
            ->setParameter('login', $login);
    
        $login = $qb->getQuery()->getResult();
        if ($login != null)
            return $login[0];
        else
            return null;
    }
}