<?php

namespace ComicReader\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * T_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_UserRepository extends EntityRepository
{
}