ComicReader_accueil:
    pattern: /
    defaults: { _controller: ComicReaderDesignBundle:Default:index, name:"index" }
ComicReader_ajout:
    pattern: ../upload
ComicReader_liste:
    pattern: ../search

