parameters:
#    comic_reader_design.example.class: ComicReader\DesignBundle\Example

services:
#    comic_reader_design.example:
#        class: %comic_reader_design.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
